version: '3.7'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - backend-service-db:/var/lib/postgresql/data

  backend-service:
    image: backend-service
    container_name: backend-service
    build:
      context: .
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '3000:3000'

volumes:
  backend-service-db:
