
@baseUrl = http://localhost:3000

### *************************************** register
# @name register
POST http://localhost:3000/register HTTP/1.1
content-type: application/json

{
    "username": "test_user",
    "email": "test@gmail.com",
    "password": "test_password"
}

### *************************************** login
 # @name login
POST {{baseUrl}}/login HTTP/1.1
content-type: application/json

{
    "email": "test@gmail.com",
    "password": "test_password"
}


### *************************************** createTodo
@jwtToken = {{login.response.body.token}}

# @name createTodo
POST {{baseUrl}}/todos HTTP/1.1
Content-Type: application/json
Authorization: token {{jwtToken}}

{
      "title": "test_todo_1",
      "due_date": "2021-10-18T16:00:00.000Z",
      "is_completed": false
}

### *************************************** getTodo
@todoId = {{createTodo.response.body.todo_id}}

# @name getTodo
GET {{baseUrl}}/todos/{{todoId}} HTTP/1.1
Authorization: token {{jwtToken}}

### *************************************** createTask

# @name createTask1
POST {{baseUrl}}/todos/{{todoId}}/tasks HTTP/1.1
Content-Type: application/json
Authorization: token {{jwtToken}}

{
  "title": "createTask1 - demo",
  "description": "description createTask",
  "due_date": "2021-09-30T16:00:00.000Z",
  "is_completed": false
}

### *************************************** getTask

# @name createTask2
POST {{baseUrl}}/todos/{{todoId}}/tasks HTTP/1.1
Content-Type: application/json
Authorization: token {{jwtToken}}

{
  "title": "createTask2 - demo",
  "description": "description createTask",
  "due_date": "2021-09-30T16:00:00.000Z",
  "is_completed": false
}

### *************************************** getAllTasks
@taskId = {{createTask2.response.body.task_id}}

# @name getTask
GET {{baseUrl}}/tasks HTTP/1.1
Authorization: token {{jwtToken}}

### *************************************** getTask
@taskId = {{createTask2.response.body.task_id}}

# @name getTask
GET {{baseUrl}}/tasks/{{taskId}} HTTP/1.1
Authorization: token {{jwtToken}}