
@baseUrl = http://localhost:3000

###
# @name register
POST http://localhost:3000/register HTTP/1.1
content-type: application/json

{
    "username": "test_user",
    "email": "test@gmail.com",
    "password": "test_password"
}

###
 # @name login
POST {{baseUrl}}/login HTTP/1.1
content-type: application/json

{
    "email": "test@gmail.com",
    "password": "test_password"
}


###


    
@jwtToken = {{login.response.body.token}}

# @name createTodo
POST {{baseUrl}}/todos HTTP/1.1
Content-Type: application/json
Authorization: token {{jwtToken}}

{
      "title": "test_todo_1",
      "due_date": "2021-10-18",
      "is_completed": false
}



###
@todoId = {{createTodo.response.body.todo_id}}

# @name getTodo
GET {{baseUrl}}/todos/{{todoId}} HTTP/1.1
Authorization: token {{jwtToken}}

###

# @name createTask

POST {{baseUrl}}/todos/{{todoId}}/tasks HTTP/1.1
Content-Type: application/json
Authorization: token {{jwtToken}}

{
    "title": "title - james1",
    "due_date": "hello",
    "description": "description - james1",
    "is_complete": false
}

###

# @name getAllTodos
GET {{baseUrl}}/todos HTTP/1.1
Authorization: token {{jwtToken}}

###

@allTodos = {{getAllTodos.response.body}}
@firstReply = {{allTodos[0].todo_id}}

# @name getFirstTodo
GET {{baseUrl}}/todos/26 HTTP/1.1
Authorization: token {{jwtToken}}